# Generated by Django 5.1.4 on 2025-01-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssfeed",
            name="approx_traffic",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="rssfeed",
            name="news_item_pictures",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rssfeed",
            name="news_item_sources",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rssfeed",
            name="news_item_titles",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rssfeed",
            name="news_item_urls",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rssfeed",
            name="picture",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="rssfeed",
            name="picture_source",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
