# Generated by Django 5.1.4 on 2025-01-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_rssfeed_approx_traffic_rssfeed_news_item_pictures_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssfeed",
            name="used",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="blogarticle",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogarticle",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="rssfeed",
            name="approx_traffic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rssfeed",
            name="link",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="rssfeed",
            name="news_item_pictures",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rssfeed",
            name="news_item_sources",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rssfeed",
            name="news_item_titles",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rssfeed",
            name="news_item_urls",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rssfeed",
            name="picture",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rssfeed",
            name="picture_source",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rssfeed",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
